1.Write a Python Program to Add Two Matrices?

In [13]:
import numpy as np
A = [[21,29,3],
     [45,5,61],
     [7,82,9]]

B = [[11,12,13],
     [14,15,16],
     [17,18,19]]

result = np.zeros((len(A),len(A[0])),dtype=int)

for i in range(len(A)):
  for j in range(len(A[i])):
    result[i][j] = int(A[i][j] + B[i][j])

print(result)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


2.Write a Python Program to Multiply Two Matrices?


In [15]:
import numpy as np
A = [[1,241,3],
     [49,5,6],
     [70,8,9]]

B = [[13,12,17],
     [14,15,16],
     [12,18,19]]

result = np.zeros((len(A),len(A[0])),dtype=int)

for i in range(len(A)):
  for j in range(len(A[i])):
    result[i][j] = int(A[i][j] * B[i][j])

print(result)

[[  13 2892   51]
 [ 686   75   96]
 [ 840  144  171]]


3.Write a Python Program to Transpose a Matrix?


In [16]:
A = [[13,24,39],
     [42,54,6],
     [76,8,94]]

result = np.zeros((len(A),len(A[0])),dtype=int)

for i in range(len(A)):
  for j in range(len(A[i])):
    result[j][i] = A[i][j]

print(result)

[[13 42 76]
 [24 54  8]
 [39  6 94]]


4.Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
string = input("Input any sentence : ")
words = string.split()
sorted_word = sorted(words)
print(sorted_word)

Input any sentence : every object will remain at rest unless compelled to change its state 
['at', 'change', 'compelled', 'every', 'its', 'object', 'remain', 'rest', 'state', 'to', 'unless', 'will']


5.Write a Python Program to Remove Punctuation From a String?


In [25]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
new_sent = ""
string = input("Input any sentence : ")
words = string.split()
i=0
for word in words:
  if i!=0 :
    new_sent += " "
  i =1
  for char in word:
    if char not in punctuations:
        new_sent += char

print(new_sent)

Input any sentence : The theory of relativity revolutionized our understanding of space, time, and gravity.
The theory of relativity revolutionized our understanding of space time and gravity
